<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Abonnement extends \App\Entity\Abonnement implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abonnementReservations' => [parent::class, 'abonnementReservations', null, 16],
        "\0".parent::class."\0".'date_debut' => [parent::class, 'date_debut', null, 16],
        "\0".parent::class."\0".'date_fin' => [parent::class, 'date_fin', null, 16],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'imageFile' => [parent::class, 'imageFile', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'abonnementReservations' => [parent::class, 'abonnementReservations', null, 16],
        'date_debut' => [parent::class, 'date_debut', null, 16],
        'date_fin' => [parent::class, 'date_fin', null, 16],
        'etat' => [parent::class, 'etat', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'imageFile' => [parent::class, 'imageFile', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
