<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'courses' => [parent::class, 'courses', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'homeAddress' => [parent::class, 'homeAddress', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'isBlocked' => [parent::class, 'isBlocked', null, 16],
        "\0".parent::class."\0".'joiningDate' => [parent::class, 'joiningDate', null, 16],
        "\0".parent::class."\0".'license' => [parent::class, 'license', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'ratings' => [parent::class, 'ratings', null, 16],
        "\0".parent::class."\0".'reponse' => [parent::class, 'reponse', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'taxis' => [parent::class, 'taxis', null, 16],
        'avis' => [parent::class, 'avis', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'courses' => [parent::class, 'courses', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'homeAddress' => [parent::class, 'homeAddress', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'isBlocked' => [parent::class, 'isBlocked', null, 16],
        'joiningDate' => [parent::class, 'joiningDate', null, 16],
        'license' => [parent::class, 'license', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'ratings' => [parent::class, 'ratings', null, 16],
        'reponse' => [parent::class, 'reponse', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'taxis' => [parent::class, 'taxis', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
