<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehicle extends \App\Entity\Vehicle implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'airConditioning' => [parent::class, 'airConditioning', null, 16],
        "\0".parent::class."\0".'brand' => [parent::class, 'brand', null, 16],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null, 16],
        "\0".parent::class."\0".'driver' => [parent::class, 'driver', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null, 16],
        "\0".parent::class."\0".'isAvailable' => [parent::class, 'isAvailable', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'licensePlate' => [parent::class, 'licensePlate', null, 16],
        "\0".parent::class."\0".'model' => [parent::class, 'model', null, 16],
        "\0".parent::class."\0".'seats' => [parent::class, 'seats', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'year' => [parent::class, 'year', null, 16],
        'airConditioning' => [parent::class, 'airConditioning', null, 16],
        'brand' => [parent::class, 'brand', null, 16],
        'color' => [parent::class, 'color', null, 16],
        'driver' => [parent::class, 'driver', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image' => [parent::class, 'image', null, 16],
        'isAvailable' => [parent::class, 'isAvailable', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'licensePlate' => [parent::class, 'licensePlate', null, 16],
        'model' => [parent::class, 'model', null, 16],
        'seats' => [parent::class, 'seats', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'year' => [parent::class, 'year', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
