<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D1U9zsJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d1U9zsJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d1U9zsJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vehicleRepository' => ['privates', 'App\\Repository\\VehicleRepository', 'getVehicleRepositoryService', true],
        ], [
            'vehicleRepository' => 'App\\Repository\\VehicleRepository',
        ]);
    }
}
