<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZcJRCwPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZcJRCwP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZcJRCwP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taxiRepository' => ['privates', 'App\\Repository\\TaxiRepository', 'getTaxiRepositoryService', true],
        ], [
            'taxiRepository' => 'App\\Repository\\TaxiRepository',
        ]);
    }
}
