<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DuNu_EHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.duNu.eH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.duNu.eH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'courseRepo' => ['privates', 'App\\Repository\\CourseRepository', 'getCourseRepositoryService', true],
            'geocoder' => ['privates', 'App\\Service\\OpenCageGeocoder', 'getOpenCageGeocoderService', true],
        ], [
            'courseRepo' => 'App\\Repository\\CourseRepository',
            'geocoder' => 'App\\Service\\OpenCageGeocoder',
        ]);
    }
}
