<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YuFNz6hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YuFNz6h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YuFNz6h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajetRepository' => ['privates', 'App\\Repository\\TrajetRepository', 'getTrajetRepositoryService', true],
        ], [
            'trajetRepository' => 'App\\Repository\\TrajetRepository',
        ]);
    }
}
