<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TqKaOKqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tqKaOKq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tqKaOKq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avi' => ['privates', '.errored..service_locator.tqKaOKq.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.tqKaOKq": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".'],
        ], [
            'avi' => 'App\\Entity\\Avis',
        ]);
    }
}
