<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Acm3OKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Acm3OK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Acm3OK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'twilioService' => ['privates', 'App\\Service\\TwilioService', 'getTwilioServiceService', true],
        ], [
            'entityManager' => '?',
            'twilioService' => 'App\\Service\\TwilioService',
        ]);
    }
}
