<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T2eST66Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t2eST66' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t2eST66'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abonnement' => ['privates', '.errored..service_locator.t2eST66.App\\Entity\\Abonnement', NULL, 'Cannot autowire service ".service_locator.t2eST66": it needs an instance of "App\\Entity\\Abonnement" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'abonnement' => 'App\\Entity\\Abonnement',
            'entityManager' => '?',
        ]);
    }
}
