<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WmUudt1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WmUudt1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WmUudt1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avi' => ['privates', '.errored..service_locator.WmUudt1.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.WmUudt1": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".'],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'avi' => 'App\\Entity\\Avis',
            'logger' => '?',
            'params' => '?',
        ]);
    }
}
