<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WXqXTgNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WXqXTgN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WXqXTgN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'recaptchaValidator' => ['privates', 'App\\Service\\RecaptchaValidator', 'getRecaptchaValidatorService', true],
        ], [
            'authenticationUtils' => '?',
            'recaptchaValidator' => 'App\\Service\\RecaptchaValidator',
        ]);
    }
}
