<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7FU7XEAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7FU7XEA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7FU7XEA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'telegram' => ['privates', 'App\\Service\\TelegramService', NULL, 'Cannot autowire service "App\\Service\\TelegramService": argument "$botToken" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'telegram' => 'App\\Service\\TelegramService',
        ]);
    }
}
