<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OpYewy6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OpYewy6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OpYewy6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'maintenance' => ['privates', '.errored..service_locator.OpYewy6.App\\Entity\\Maintenance', NULL, 'Cannot autowire service ".service_locator.OpYewy6": it needs an instance of "App\\Entity\\Maintenance" but this type has been excluded in "config/services.yaml".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'em' => '?',
            'maintenance' => 'App\\Entity\\Maintenance',
            'security' => '?',
        ]);
    }
}
