<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A59gyzWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A59gyzW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A59gyzW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
            'taxi' => ['privates', '.errored..service_locator.A59gyzW.App\\Entity\\Taxi', NULL, 'Cannot autowire service ".service_locator.A59gyzW": it needs an instance of "App\\Entity\\Taxi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
            'taxi' => 'App\\Entity\\Taxi',
        ]);
    }
}
