<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0488DqBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0488DqB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0488DqB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reponse' => ['privates', '.errored..service_locator.0488DqB.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.0488DqB": it needs an instance of "App\\Entity\\Reponse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reponse' => 'App\\Entity\\Reponse',
        ]);
    }
}
