<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vp8xSL3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vp8xSL3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vp8xSL3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'taxi' => ['privates', '.errored..service_locator.vp8xSL3.App\\Entity\\Taxi', NULL, 'Cannot autowire service ".service_locator.vp8xSL3": it needs an instance of "App\\Entity\\Taxi" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'taxi' => 'App\\Entity\\Taxi',
        ]);
    }
}
