<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonnementReservation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hWMg91g.App\Entity\AbonnementReservation' shared service.
     *
     * @return \App\Entity\AbonnementReservation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hWMg91g": it needs an instance of "App\\Entity\\AbonnementReservation" but this type has been excluded in "config/services.yaml".');
    }
}
