<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthenticationSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\AuthenticationSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\AuthenticationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'AuthenticationSubscriber.php';

        $a = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['App\\EventSubscriber\\AuthenticationSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\AuthenticationSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\AuthenticationSubscriber'] = new \App\EventSubscriber\AuthenticationSubscriber(($container->services['router'] ?? self::getRouterService($container)), $a);
    }
}
