<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBadWordFilterServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\BadWordFilterService' shared autowired service.
     *
     * @return \App\Service\BadWordFilterService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'BadWordFilterService.php';

        return $container->privates['App\\Service\\BadWordFilterService'] = new \App\Service\BadWordFilterService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), 'https://www.purgomalum.com/service/plain');
    }
}
