<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttplug_ClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'httplug.client' shared service.
     *
     * @return \Http\Client\Common\HttpMethodsClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psr'.\DIRECTORY_SEPARATOR.'http-client'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'httplug'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HttpClient.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HttpMethodsClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HttpMethodsClient.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'httplug'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HttpAsyncClient.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'PluginClient.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'httplug-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ClientFactory'.\DIRECTORY_SEPARATOR.'ClientFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'httplug-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Collector'.\DIRECTORY_SEPARATOR.'ProfileClientFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'httplug-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ClientFactory'.\DIRECTORY_SEPARATOR.'AutoDiscoveryFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Plugin.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'ContentLengthPlugin.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Plugin'.\DIRECTORY_SEPARATOR.'RedirectPlugin.php';

        return $container->services['httplug.client'] = new \Http\Client\Common\HttpMethodsClient(($container->privates['Http\\Client\\Common\\PluginClientFactory'] ?? self::getPluginClientFactoryService($container))->createClient((new \Http\HttplugBundle\Collector\ProfileClientFactory(new \Http\HttplugBundle\ClientFactory\AutoDiscoveryFactory(), ($container->privates['httplug.collector.collector'] ??= new \Http\HttplugBundle\Collector\Collector(0)), ($container->privates['httplug.collector.formatter'] ?? self::getHttplug_Collector_FormatterService($container)), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true))))->createClient([]), [new \Http\Client\Common\Plugin\ContentLengthPlugin(), new \Http\Client\Common\Plugin\RedirectPlugin(['preserve_header' => true, 'use_default_for_multiple' => true])], ['client_name' => 'app']), ($container->services['httplug.psr17_request_factory'] ?? $container->load('getHttplug_Psr17RequestFactoryService')), ($container->services['httplug.psr17_stream_factory'] ?? $container->load('getHttplug_Psr17StreamFactoryService')));
    }
}
