<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_Twig_Extension_Oauth_RuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.twig.extension.oauth.runtime' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Twig\Extension\OAuthRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'OAuthRuntime.php';

        $a = ($container->privates['hwi_oauth.security.oauth_utils'] ?? $container->load('getHwiOauth_Security_OauthUtilsService'));

        if (isset($container->privates['hwi_oauth.twig.extension.oauth.runtime'])) {
            return $container->privates['hwi_oauth.twig.extension.oauth.runtime'];
        }

        return $container->privates['hwi_oauth.twig.extension.oauth.runtime'] = new \HWI\Bundle\OAuthBundle\Twig\Extension\OAuthRuntime($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
