<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwner_GoogleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.resource_owner.google' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GoogleResourceOwner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwnerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwner'.\DIRECTORY_SEPARATOR.'AbstractResourceOwner.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwner'.\DIRECTORY_SEPARATOR.'GenericOAuth2ResourceOwner.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwner'.\DIRECTORY_SEPARATOR.'GoogleResourceOwner.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'RequestDataStorageInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'RequestDataStorage'.\DIRECTORY_SEPARATOR.'SessionStorage.php';

        return $container->privates['hwi_oauth.resource_owner.google'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GoogleResourceOwner(($container->privates['.debug.hwi_oauth.http_client'] ?? self::get_Debug_HwiOauth_HttpClientService($container)), ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), ['client_id' => $container->getEnv('OAUTH_GOOGLE_CLIENT_ID'), 'client_secret' => $container->getEnv('OAUTH_GOOGLE_CLIENT_SECRET'), 'scope' => 'email profile', 'options' => ['csrf' => true, 'access_type' => 'online', 'display' => 'popup'], 'paths' => []], 'google', new \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
