<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwnermap_MainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hwi_oauth.resource_ownermap.main' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMap
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'ResourceOwnerMapInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'ResourceOwnerMap.php';

        return $container->services['hwi_oauth.resource_ownermap.main'] = new \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMap(($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), $container->parameters['hwi_oauth.resource_owners'], $container->parameters['hwi_oauth.resource_ownermap.configured.main'], new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'google' => ['privates', 'hwi_oauth.resource_owner.google', 'getHwiOauth_ResourceOwner_GoogleService', true],
        ], [
            'google' => '?',
        ]));
    }
}
