<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwnermapLocatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'hwi_oauth.resource_ownermap_locator' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMapLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'ResourceOwnerMapLocator.php';

        $container->privates['hwi_oauth.resource_ownermap_locator'] = $instance = new \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMapLocator();

        $instance->set('main', ($container->services['hwi_oauth.resource_ownermap.main'] ?? $container->load('getHwiOauth_ResourceOwnermap_MainService')));

        return $instance;
    }
}
