<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'HWI\Bundle\OAuthBundle\Controller\LoginController' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Controller\LoginController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'LoginController.php';

        return $container->services['HWI\\Bundle\\OAuthBundle\\Controller\\LoginController'] = new \HWI\Bundle\OAuthBundle\Controller\LoginController(($container->privates['security.authentication_utils'] ?? $container->load('getSecurity_AuthenticationUtilsService')), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['twig'] ?? self::getTwigService($container)), false, 'IS_AUTHENTICATED_REMEMBERED');
    }
}
