<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OpYewy6.App\Entity\Maintenance' shared service.
     *
     * @return \App\Entity\Maintenance
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OpYewy6": it needs an instance of "App\\Entity\\Maintenance" but this type has been excluded in "config/services.yaml".');
    }
}
