<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenCageGeocoderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OpenCageGeocoder' shared autowired service.
     *
     * @return \App\Service\OpenCageGeocoder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OpenCageGeocoder.php';

        return $container->privates['App\\Service\\OpenCageGeocoder'] = new \App\Service\OpenCageGeocoder($container->getEnv('OPENCAGE_API_KEY'));
    }
}
