<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ReportController' shared autowired service.
     *
     * @return \App\Controller\ReportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ReportController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ReportService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Dompdf.php';

        $a = ($container->privates['App\\Repository\\RatingRepository'] ?? $container->load('getRatingRepositoryService'));
        $b = ($container->privates['App\\Repository\\CourseRepository'] ?? $container->load('getCourseRepositoryService'));
        $c = ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'));

        $container->services['App\\Controller\\ReportController'] = $instance = new \App\Controller\ReportController(new \App\Service\ReportService($a, $b, $c, $b, $a, $c), new \Dompdf\Dompdf(['isRemoteEnabled' => true]));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ReportController', $container));

        return $instance;
    }
}
