<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TelegramService' shared autowired service.
     *
     * @return \App\Service\TelegramService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\TelegramService": argument "$botToken" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
