<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTextToSpeechServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TextToSpeechService' shared autowired service.
     *
     * @return \App\Service\TextToSpeechService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TextToSpeechService.php';

        return $container->privates['App\\Service\\TextToSpeechService'] = new \App\Service\TextToSpeechService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
