<?php

namespace Container1dIWENC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A59gyzW.App\Entity\Taxi' shared service.
     *
     * @return \App\Entity\Taxi
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A59gyzW": it needs an instance of "App\\Entity\\Taxi" but this type has been excluded in "config/services.yaml".');
    }
}
